#!/usr/bin/env ruby -s
# NotRuby interpreter
$:.unshift File.expand_path("..", __FILE__)
require "interpreter"
require "readline"

if $h # -h option
  abort <<USAGE
Usage:

  ./notruby # start REPL
  ./notruby file.rb
  ./notruby -e='code'

USAGE
end

# Eval some code
# $e = # -e option
if $e
  Interpreter.new.eval($e)

elsif ARGV.first
  Interpreter.new.eval(File.read(ARGV.first))

# Start the REPL, read-eval-print-loop, or interactive interpreter
else
  puts "NotRuby REPL, CTRL+C to quit"
  interpreter = Interpreter.new
  loop do
    line = Readline::readline(">> ")              # read
    Readline::HISTORY.push(line)
    begin
      result = interpreter.eval(line).ruby_value  # eval
      puts "=> #{result.inspect}"                 # print
    rescue => error
      puts error
    end
  end                                             # loop

end